---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
spec:
  encryptedData:
    apiKey: {{ .Values.cloudflare.encrypted_api_key }}
  template:
    metadata:
      name: cloudflare-api-key