tenantControlPlane:
  name: ""
  dataStore: default
  
  kubernetes:
    version: "v1.34.0"
  
  gateway:
    parentRef:
      name: traefik-gateway
      namespace: traefik
      sectionName: k8s

    ipAllowList: []
    hostname: