{{ if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  secretName: {{ include "microservice.fullname" . }}-cert
  commonName: {{ required "The certificate CN is required!" .Values.certificate.commonName }}
  dnsNames:
  {{- range (append .Values.certificate.dnsNames .Values.certificate.commonName) }}
  - {{ . | quote }}
  {{- end }}
  renewBefore: 360h0m0s
  duration: 2160h0m0s
  {{ if .Values.certificate.clusterIssuer -}}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer }}
    kind: ClusterIssuer
  {{ else if .issuer -}}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: Issuer
  {{- end -}}
{{ end -}}