{{- if or .Values.config .Values.rawConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if hasSuffix ".yaml" $key}}
  {{ $key }}: |-
  {{- $value | toYaml | nindent 4}}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
  {{- end }}

  {{- range $key, $value := .Values.rawConfig }}
  {{ $key }}: |-
  {{- $value | nindent 6 }}
  {{- end }}
{{- end }}