{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "watch", "list"]
  {{- if .Values.serviceAccount.cudResources }}
  - apiGroups: [""]
    resources: {{ .Values.serviceAccount.cudResources | toJson }}
    verbs: ["create", "update", "patch", "delete"]
  {{- end }}
  {{- if .Values.serviceAccount.roleRules }}
  {{- toYaml .Values.serviceAccount.roleRules | nindent 2 }}
  {{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "microservice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "microservice.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.serviceAccount.clusterRoleRules }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
rules:
  {{- if .Values.serviceAccount.clusterRoleRules }}
  {{- toYaml .Values.serviceAccount.clusterRoleRules | nindent 2 }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "microservice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "microservice.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
