{{- if .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  encryptedData:
    {{- with .Values.secrets }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      name: {{ include "microservice.fullname" . }}
{{- end}}