---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.cloudflare.tunnel_token_secret_ref.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    token: {{ .Values.cloudflare.tunnel_token_secret_ref.encrypted_token }}
  template:
    metadata:
      name: {{ .Values.cloudflare.tunnel_token_secret_ref.name }}
      namespace: {{ .Release.Namespace }}
